defaults: &defaults
  og:
    url:      http://hiddeste.local.jp:3456/
    title:    Hiddeste
    type:     article
    image:    http://hiddeste.local.jp:3456/assets/logo158x158.png
    site_name:  Hiddeste
    description: This application manages the information and participants of the event.
    article:
      author:  <%= ENV['HIDASTE_FACEBOOK_APP_OWNER'] %>
  facebook:
    app:
      id:     <%= ENV['HIDASTE_FACEBOOK_APP_ID'] %>
      secret: <%= ENV['HIDASTE_FACEBOOK_APP_SECRET'] %>
  twitter:
    card: summary
    site:
      name: <%= ENV['HIDASTE_TWITTER_SITE_USER'] %>
      id:   <%= ENV['HIDASTE_TWITTER_SITE_USER_ID'] %>
    api:
      key:    <%= ENV['HIDASTE_TWITTER_API_KEY'] %>
      secret: <%= ENV['HIDASTE_TWITTER_API_SECRET'] %>
    owner:
      name: <%= ENV['HIDASTE_TWITTER_OWNER'] %>
      id:   <%= ENV['HIDASTE_TWITTER_OWNER_ID'] %>
  contact:
    email: hiddeste@hiddeste.local.jp

development:
  <<: *defaults

production:
  <<: *defaults
  og:
    url:      https://hiddeste.herokuapp.com/
    title:    Hiddeste
    type:     article
    image:    https://hiddeste.herokuapp.com/assets/logo158x158.png
    site_name:  Hiddeste
    description: This application manages the information and participants of the event.
    article:
      author:  <%= ENV['HIDASTE_FACEBOOK_APP_OWNER'] %>
  contact:
    email: hiddeste@gmail.com
